services:
  - type: web
    name: flask-portfolio
    env: python
    buildCommand: ""
    startCommand: "gunicorn PythonProject.myapp.app:app"
    envVars:
      - key: FLASK_ENV
        value: production
