services:
  - type: web
    name: flask-portfolio
    env: python
    buildCommand: ""
    startCommand: "python myapp/create_db.py && gunicorn myapp.app:app"
    envVars:
      - key: FLASK_ENV
        value: production
